export default {
    products : [
        {
            _id: '1',
            name: 'Anayet',
            category:'Shirts',
            image:'./images/product-1.jpg',
            price:60,
            ratting:4.5,
            numReviews:10,
            countInStock:6,
        },
        {
            _id: '2',
            name: 'ANAYET',
            category:'Shirts',
            image:'./images/product-2.jpg',
            price:550,
            ratting:4.5,
            numReviews:10,
            countInStock:6,
        },
        {
            _id: '3',
            name: 'Montserrat',
            category:'Shirts',
            image:'./images/product-3.jpg',
            price:20,
            ratting:4.5,
            numReviews:10,
            countInStock:6,
        },
        {
            _id: '4',
            name: 'Leyre',
            category:'Shirts',
            image:'./images/product-4.jpg',
            price:10,
            ratting:4.5,
            numReviews:10,
            countInStock:6,
        },
        {
            _id: '5',
            name: 'Mapa',
            category:'Cars',
            image:'./images/product-5.jpg',
            price:35,
            ratting:4.5,
            numReviews:10,
            countInStock:6,
        },
        {
            _id: '6',
            name: 'ANAYET',
            category:'Shirts',
            image:'./images/product-6.jpg',
            price:60,
            ratting:2.5,
            numReviews:8,
            countInStock:4,
        }
    ]
}